In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(type(arr))      # 查看类型
print(arr.shape)      # 数组形状
print(arr.dtype)      # 数据类型

<class 'numpy.ndarray'>
(4,)
int64


In [9]:
# 从列表创建
arr1 = np.array([1, 2, 3])

# 创建全 0 数组
arr2 = np.zeros(9)

# 创建全 1 数组
arr3 = np.ones(8)

# 创建连续数字
arr4 = np.arange(0, 12, 2)
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[1 2 3]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  2  4  6  8 10]


In [3]:
arr = np.array([1, 2, 3, 4])

print(arr + 10)
print(arr * 2)
print(arr.mean())
print(arr.sum())
print(arr.max())

[11 12 13 14]
[2 4 6 8]
2.5
10
4


In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr.shape)  #数组的属性
print(arr.ndim)      # 维度
print(arr.size)     # 元素个数
print(arr.dtype)    # 数据类型
print(arr.mean())  #数组方法--求平均值
print(arr.std())  #数组方法--标准差
print(arr * 5)   #数组运算
print(arr[-3:-1])   #数组切片
print(np.sqrt(arr))     # 开平方
print(np.log(arr))      # 取对数
print(np.exp(arr))      # 指数



(4,)
1
4
int64
25.0
11.180339887498949
[ 50 100 150 200]
[20 30]
[3.16227766 4.47213595 5.47722558 6.32455532]
[2.30258509 2.99573227 3.40119738 3.68887945]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]


In [17]:
import numpy as np

# 1. 初始化数组 (7个元素)
arr = np.arange(1, 21)
print(f"原始数组 arr: {arr}")
print(f"原始形状 arr.shape: {arr.shape}")

# 2. 使用 reshape (必须提供新形状)
# 7个元素不能形成完美的矩形 (如2x?)，但可以形成 7x1
arr_reshaped = arr.reshape(5, 4)
print(f"\nReshaped 数组 arr_reshaped: \n{arr_reshaped}")
print(f"新形状 arr_reshaped.shape: {arr_reshaped.shape}")

# 3. 使用 flatten (生成数组的副本，保持 arr 不变)
# 我们对 arr_reshaped 进行 flatten
arr_flattened = arr_reshaped.flatten()
print(f"\nFlattened 数组 arr_flattened: {arr_flattened}")
print(f"Flattened 形状 arr_flattened.shape: {arr_flattened.shape}")

# 原始数组 arr 保持不变
print(f"\n原始数组 arr 最终值 (未被 reshape 或 flatten 改变): {arr}")


原始数组 arr: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
原始形状 arr.shape: (20,)

Reshaped 数组 arr_reshaped: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
新形状 arr_reshaped.shape: (5, 4)

Flattened 数组 arr_flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Flattened 形状 arr_flattened.shape: (20,)

原始数组 arr 最终值 (未被 reshape 或 flatten 改变): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
